### ISSUE TITLE
Visibility of website-name in "Manage access"

### ISSUE THREAD

**Issue by HenningBMS** [PiwikPRO/plugin-WebsiteGroups#1]
I'm using the new feature "group". 
If the chosen name of a group is longer than 20 characters the name of the website is not longer visible in the pulddwon menu in the area "Manage access".
![piwik_user](https://cloud.githubusercontent.com/assets/9717272/5026997/63fe74a8-6b2a-11e4-87af-0734abf264ed.png)

**Comment by mattab** [comment]
Thanks for the report. This will be fixed in Piwik core in: https://github.com/piwik/piwik/issues/8569
