### ISSUE TITLE
new group 

### ISSUE THREAD

**Issue by imoullet** [PiwikPRO/plugin-WebsiteGroups#2]
I cannot find the way to create a new group for websites .

I use piwik 2.9 and the latest version of plugin website groups 

Any help welcome

**Comment by jfromm** [comment]
I have the same issue with piwik 2.10.0, the latest plugin version and php 5.3.3. Anything idea?

**Comment by tsteur** [comment]
Can you see the `Edit` icon when hovering a website name? See https://github.com/PiwikPRO/plugin-WebsiteGroups/blob/master/screenshots/All_Websites_Dashboard.png afterwards there should be this menu https://github.com/PiwikPRO/plugin-WebsiteGroups/blob/master/screenshots/Create_Or_Assign_Group.png where you can create / add a new group. Usability could be probably improved (eg by adding it to Settings => Websites as well etc)

**Comment by imoullet** [comment]
The plugin websitesgroup is activated but I have NO edit icon near the website name. Is this feature only available for piwik Pro subscriber?

**Comment by imoullet** [comment]
PS: Sorry.. I DO have the edit icon.. I was looking at the administration websites list not the all websites dashboard .. Sorry for the confusion. But does that mean that everyone with read access can create their groups not only the administrator.

**Comment by jfromm** [comment]
Ah yes, now I see the edit icon. Thanks for your help.

**Comment by tsteur** [comment]
@imoullet it is only possible for users having Super User access
